name: 'Install Terragrunt'
description: 'Installs the specified version of Terragrunt'
inputs:
  terragrunt-version:  # id of input
    description: 'Version of Terragrunt you want to install'
    required: true
    default: 'v0.47.0'
runs:
  using: "composite"
  steps:
    - run: echo Version ${{ inputs.terragrunt-version }}.
      shell: bash

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: install.sh
      shell: bash
