name: 'Install Terragrunt'
description: 'Installs the specified version of Terragrunt'
inputs:
  terragrunt-version:
    description: 'Version of Terragrunt you want to install'
    required: true
    default: 'v0.47.0'
runs:
  using: "composite"
  steps:
    - id: path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH # Set the path so that the `install.sh` works
      shell: bash
    - id: install
      run: install.sh
      shell: bash
      env:
        VERSION: ${{ inputs.terragrunt-version }}
